# -*- coding: utf-8 -*-
"""intro to scikit_learn.iptynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b00rgedHd0DhCqV9jpjAy4iwuetXsFij

# **What Actually going to learn**

1.    An end to end Scikit work flow
1. getting the data ready
1.   Choose the right/estimater or algo for problem
2.   Fit the model/ algo use it for predictions
1.   Evaluating the Model
2.   Improve the model
1.   Save and load the Model
2.   Putting all together
"""

import numpy as np
import pandas as pd

"""**Importing the data using pandas**"""

heart_disease = pd.read_csv('heart-disease.csv')

"""**Spliting the data into X and y**

1.   X = Features of the Data
2.   y = lable of data or target of data


"""

x = heart_disease.drop('target', axis=1)
y = heart_disease['target']

from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=100)
clf.get_params()

"""# **Simpler way easily understandble:**


train_test_split simply chops your full data (x features and y labels) into two piles: 80% for training your model and 30% for testing it.

What Happens Step-by-Step
Takes your entire x and y datasets.

Randomly picks 80% → becomes x_train + y_train (teach the model).

Rest 20% → x_test + y_test (quiz the model later).
​

Why This Ratio
test_size=0.2 = keep 20% aside unseen. More train data = smarter model, enough test data = fair score.

Like school: Study 70% of notes, quiz yourself on held-back 30%.
"""

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

"""clf.fit(x_train, y_train) tells your "smart guesser" (the clf model) to study the training examples so it learns the patterns.

Like Teaching a Dog a Trick
Imagine x_train = photos of cats/dogs, y_train = correct labels ("cat" or "dog").

fit() = you show the dog 100 photos repeatedly: "This is cat! That's dog!"

After fit(), the dog (model) remembers patterns like "whiskers = cat".
​

What Changes Inside
The model tweaks its "brain settings" (numbers called parameters) to match examples perfectly. Now it's ready to guess new photos with clf.predict(x_test).
"""

clf.fit(x_train, y_train);

y_pre = clf.predict(x_test)

y_pre

clf.score(x_train, y_train)

clf.score(x_test, y_test)

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(classification_report(y_test, y_pre))

print(confusion_matrix(y_test, y_pre))

print(accuracy_score(y_test, y_pre))

np.random.seed(42)
for i in range (5,105, 5):
  print(f"Trying model with {i} estimators...")
  clf = RandomForestClassifier(n_estimators=i).fit(x_train, y_train)
  print(f"Model accuracy on test set: {clf.score(x_test, y_test) *100:.2f}")
  print(' ')

import pickle

pickle.dump(clf, open('random_forest_model_1.pkl', 'wb'))

load_model = pickle.load(open('random_forest_model_1.pkl', 'rb'))
load_model.score(x_test, y_test)